import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.product': '产品',
    'nav.shortDrama': '短剧',
    'nav.cases': '案例',
    'nav.about': '关于',
    'nav.workspace': '工作台',
    'nav.login': '登录',
    'nav.logout': '退出',
    'nav.pricing': '定价',
    'home.pricingLink': '查看定价与套餐',

    // Home
    'home.hero.title': '面向出海团队的 AI 营销与商品增长工作台',
    'home.hero.subtitle':
      '把市场洞察、内容制作、商品分析与执行承接放进同一套工作流，帮助团队更快发现机会、产出内容并优化商品。',
    'home.hero.primary': '进入工作台',
    'home.hero.secondary': '查看定价',
    'home.capabilities.title': '产品能力总览',
    'home.capabilities.subtitle':
      '从市场判断到内容与商品动作，GlobalPulseAI 用同一套工作流把关键环节串起来。',
    'home.capabilities.l1': '营销分析：把分散的市场信号整理成需求、趋势与竞争判断。',
    'home.capabilities.l2': '内容制作：把洞察转成内容方向、选题和可执行表达。',
    'home.capabilities.l3': '商品分析：把商品页、评论和卖点转成优化建议。',
    'home.capabilities.l4': '工作流沉淀：把分析、历史与下一步动作留在同一个工作台里。',
    'home.howItWorks.heading': '工作流程',
    'home.step1': '输入你的市场、内容或商品问题',
    'home.step2': '系统整合多来源信号并完成分析',
    'home.step3': '输出可执行的内容、商品与下一步动作',
    'home.output.title': '你最终会得到什么',
    'home.output.b1': '市场洞察：需求、趋势、竞争空白与用户痛点',
    'home.output.b2': '内容方向：可尝试的选题、表达角度与内容方向',
    'home.output.b3': '商品建议：标题、主图、卖点、评论反馈与页面优化建议',
    'home.output.b4': '执行承接：历史分析、结论沉淀与下一步动作管理',
    'home.cta.title': '下一步',
    'home.cta.desc': '进入工作台开始协作；需要选型时可查看定价，或先了解产品能力。',
    'home.cta.product': '了解产品',
    'home.analyzing': '正在分析市场数据...',
    'home.analyzing.en': 'Analyzing market data...',
    'home.analysisFailed': '分析失败，请稍后重试',
    'home.analysisFailed.en': 'Analysis failed, please try again later',

    // Product
    'product.title': '产品功能',
    'product.subtitle': '全方位的市场分析解决方案，助您把握营销机遇',
    'product.feature1.title': '需求分析',
    'product.feature1.desc': '深入分析 Reddit 社区讨论，挖掘用户真实需求和市场痛点，精准把握目标用户心声',
    'product.feature1.f1': '话题提取',
    'product.feature1.f2': '情绪分析',
    'product.feature1.f3': '趋势识别',
    'product.feature2.title': '竞争分析',
    'product.feature2.desc': '全面扫描 SEO 内容供给，分析竞争对手策略，识别市场空白和机会点',
    'product.feature2.f1': '关键词分析',
    'product.feature2.f2': '内容统计',
    'product.feature2.f3': '差距识别',
    'product.feature3.title': '智能推荐',
    'product.feature3.desc': '基于需求和供给的对比分析，自动生成高价值内容创意，提升营销效率',
    'product.feature3.f1': '创意生成',
    'product.feature3.f2': '格式多样化',
    'product.feature3.f3': '理由说明',
    'product.feature4.title': '数据洞察',
    'product.feature4.desc': '整合多维数据源，提供机会得分、市场趋势等关键指标，辅助决策',
    'product.feature4.f1': '可视化报表',
    'product.feature4.f2': '数据导出',
    'product.feature4.f3': '历史追踪',
    'product.cta.title': '开始使用',
    'product.cta.desc': '立即体验 GlobalPulse AI 的强大分析能力，发现您的下一个市场机会',
    'product.cta.button': '免费试用',

    // Cases
    'cases.title': '成功案例',
    'cases.subtitle': '看看其他企业如何使用 GlobalPulse AI 取得成果',
    'cases.tag1': 'SaaS',
    'cases.case1.title': 'AI 工具推广',
    'cases.case1.client': '某 AI 编程助手公司',
    'cases.case1.desc': '通过分析 Reddit 讨论热点，发现用户对 AI 编程工具的真实需求，生成针对性内容策略。',
    'cases.tag2': '电商',
    'cases.case2.title': 'Shopify SEO 优化',
    'cases.case2.client': '某跨境电商平台',
    'cases.case2.desc': '分析 SEO 供给与 Reddit 需求的差距，找到低竞争高价值的关键词，优化内容策略。',
    'cases.tag3': '营销',
    'cases.case3.title': '内容营销转型',
    'cases.case3.client': '某营销自动化服务商',
    'cases.case3.desc': '利用智能内容创意生成，快速产出高质量营销内容，显著提升市场响应速度。',
    'cases.tag4': '教育',
    'cases.case4.title': '在线课程推广',
    'cases.case4.client': '某在线教育平台',
    'cases.case4.desc': '分析学习者在 Reddit 的讨论内容，发现课程推广的痛点和机会，精准定位目标用户。',
    'cases.tag5': '科技',
    'cases.case5.title': '开发者工具推广',
    'cases.case5.client': '某开发者工具厂商',
    'cases.case5.desc': '通过分析开发者社区的讨论趋势，创建符合需求的内容，提升品牌在目标受众中的认知度。',
    'cases.tag6': '咨询',
    'cases.case6.title': 'B2B 营销优化',
    'cases.case6.client': '某 B2B 软件服务商',
    'cases.case6.desc': '分析 B2B 决策者的关注点，生成专业内容，提升线索质量和转化效率。',
    'cases.cta.title': '成为下一个成功案例',
    'cases.cta.desc': '立即开始使用 GlobalPulse AI，发现属于您的市场机会',
    'cases.cta.button': '开始免费试用',
    'cases.r1.label': '内容机会',
    'cases.r2.label': '流量增长',
    'cases.r3.label': '转化率提升',
    'cases.r4.label': '关键词机会',
    'cases.r5.label': '搜索排名',
    'cases.r6.label': 'ROI 提升',
    'cases.r7.label': '创意生成',
    'cases.r8.label': '创作效率',
    'cases.r9.label': '用户互动',
    'cases.r10.label': '市场洞察',
    'cases.r11.label': '报名转化',
    'cases.r12.label': '内容产出',
    'cases.r13.label': '社群影响力',
    'cases.r14.label': '自然流量',
    'cases.r15.label': '品牌认知',
    'cases.r16.label': '线索质量',
    'cases.r17.label': '销售周期',
    'cases.r18.label': '市场覆盖',

    // About
    'about.title': '关于我们',
    'about.subtitle': '用 AI 技术赋能市场营销，帮助企业在数据中发现机遇',
    'about.hero.primary': '进入工作台',
    'about.hero.secondary': '查看定价',
    'about.story.eyebrow': '故事与初衷',
    'about.story.title': '为什么做 GlobalPulse AI',
    'about.story.p1':
      '市场与内容决策越来越依赖实时信号，但数据分散、工具割裂，团队往往难以快速形成可执行的判断。我们希望用 AI 将多源信息整合为清晰洞察，并落到可试的内容与策略动作上。',
    'about.story.p2':
      '从自然语言处理到多维数据整合，我们持续打磨分析流程：让营销与创作者少花时间整理数据，多把时间放在创意与策略上。',
    'about.mission.title': '我们的使命',
    'about.mission.desc': 'GlobalPulse AI 致力于通过先进的 AI 技术，帮助企业和营销人员实时洞察市场动态，深度分析用户需求，发现内容机会，从而做出更明智的营销决策。我们相信，数据驱动的营销策略是未来成功的关键。',
    'about.values.title': '我们的价值观',
    'about.values.precise.title': '精准',
    'about.values.precise.desc': '基于真实数据和 AI 分析，提供精准的市场洞察和内容建议，拒绝盲目猜测',
    'about.values.efficient.title': '高效',
    'about.values.efficient.desc': '自动化分析流程，大幅提升营销效率，让团队专注于创意和策略',
    'about.values.reliable.title': '可靠',
    'about.values.reliable.desc': '数据来源权威，分析算法严谨，结果可验证，值得您信赖',
    'about.why.title': '为什么选择我们',
    'about.why.1.title': 'AI 驱动的分析',
    'about.why.1.desc': '利用最先进的自然语言处理和机器学习技术，深度挖掘社交媒体和 SEO 数据',
    'about.why.2.title': '多维数据整合',
    'about.why.2.desc': '同时分析 Reddit、SEO 等多个数据源，提供全方位的市场视角',
    'about.why.3.title': '实时市场洞察',
    'about.why.3.desc': '捕捉最新趋势和热点，帮助您快速响应市场变化',
    'about.why.4.title': '可操作的建议',
    'about.why.4.desc': '不只是数据报告，更提供可直接执行的内容创意和策略建议',
    'about.contact.title': '联系我们',
    'about.contact.email': '邮箱联系',
    'about.contact.email.value': 'chuckyang360@gmail.com',
    'about.contact.follow': '关注我们',
    'about.contact.follow.value': '@GlobalPulseAI',
    'about.contact.address': '公司地址',
    'about.contact.address.value': '杭州市越响信息科技有限公司',
    'about.contact.person': '联系人',
    'about.contact.person.value': '杨克',
    'about.cta.title': '准备好开始了吗？',
    'about.cta.desc': '加入 GlobalPulse AI，让数据驱动您的营销决策',
    'about.cta.button': '免费开始使用',

    // Pricing & Checkout
    'pricing.page.eyebrow': 'Plans',
    'pricing.page.title': '选择适合你的方案',
    'pricing.page.subtitle':
      'GlobalPulseAI 面向市场情报、商品分析、内容策略与协作效率，帮助你把跨平台信号转化为可执行的增长动作。',
    'pricing.page.subtitleShort': '市场情报、商品分析与内容策略，按团队规模选择方案。',
    'pricing.page.proOneLiner': '需要更高频洞察与深度分析时，多数团队选择 Pro。',
    'pricing.page.footerNote':
      '价格为占位展示，支付通道接入后生效。用量与限制以账户及协议为准；有疑问请联系销售。',
    'pricing.plan.pro.cardHint': '匹配每周多次分析、多商品并行迭代的工作节奏。',
    'pricing.pro.section.title': '为什么多数团队从 Pro 开始',
    'pricing.pro.section.body':
      '创作者、卖家与运营需要稳定节奏：把趋势、舆情与商品页问题，变成可迭代的优化与内容动作。Pro 在用量与深度上更匹配这一工作方式。',
    'pricing.modules.sectionTitle': '能力全景',
    'pricing.toggle.monthly': '按月',
    'pricing.toggle.yearly': '按年',
    'pricing.toggle.save': '省 {n}%',
    'pricing.billing.perMonthShort': '/月',
    'pricing.billing.perYearShort': '/年',
    'pricing.billing.equivalentMonthly': '约合 ${n}/月（按年计费）',
    'pricing.plan.pro.badge': '推荐',
    'pricing.cta.checkout': '继续结算',
    'pricing.cta.contact': '联系销售',
    'pricing.usage.heading': '用量与权益（预览）',
    'pricing.plan.free.name': 'Free',
    'pricing.plan.free.audience': '适合：个人探索与验证',
    'pricing.plan.free.tagline': '先验证市场是否值得投入，再决定是否加码。',
    'pricing.plan.free.priceHint': '永久免费',
    'pricing.plan.free.f1': '把跨平台趋势与讨论，整理成可跟进的线索',
    'pricing.plan.free.f2': '用商品链接得到可执行的初判，而不只是数据罗列',
    'pricing.plan.free.f3': '把信号变成可试的内容角度，降低冷启动成本',
    'pricing.plan.free.f4': '保存关键片段，便于下次继续推演',
    'pricing.plan.pro.name': 'Pro',
    'pricing.plan.pro.audience': '适合：卖家、创作者与运营',
    'pricing.plan.pro.tagline': '把「发现趋势 → 理解商品 → 落地动作」变成可持续节奏。',
    'pricing.plan.pro.whyRecommended':
      '独立卖家与创作者往往同时跑多平台与多商品实验；Pro 提供更高频的洞察与更深的商品分析，把时间花在改标题、素材与内容，而不是反复找同一份图表。',
    'pricing.plan.pro.f1': '联动 Reddit、X 与搜索信号，判断需求是否真实',
    'pricing.plan.pro.f2': '把商品页解析成可优先处理的优化建议',
    'pricing.plan.pro.f3': '把洞察落成可发布的角度、钩子与标题',
    'pricing.plan.pro.f4': '用报告与历史对齐「试了啥」与「下一步改啥」',
    'pricing.plan.pro.f5': '优先体验新能力，保持工作流不过时',
    'pricing.plan.team.name': 'Team',
    'pricing.plan.team.audience': '适合：多品牌、多店铺与跨职能协作团队',
    'pricing.plan.team.tagline': '为多人协作与规模化用量预留空间：共享上下文、统一节奏、可扩展配额。',
    'pricing.team.priceLine': '联系销售',
    'pricing.team.priceHint': '按席位、用量与合规需求定制',
    'pricing.plan.team.f1': '共享市场与商品上下文，减少重复沟通',
    'pricing.plan.team.f2': '按团队节奏扩展分析容量与覆盖范围',
    'pricing.plan.team.f3': '统一账单、权限与采购流程',
    'pricing.plan.team.f4': '把历史沉淀为团队可复用的知识',
    'pricing.plan.team.f5': '客户成功与优先支持，配合规模化落地',
    'pricing.module.mi.title': 'Market Intelligence',
    'pricing.module.mi.b1': '发现跨平台趋势与话题走向',
    'pricing.module.mi.b2': '追踪 Reddit、X 与搜索信号中的讨论与情绪',
    'pricing.module.mi.b3': '识别需求、情绪与机会窗口',
    'pricing.module.pa.title': 'Product Analysis',
    'pricing.module.pa.b1': '解析主流电商平台商品链接',
    'pricing.module.pa.b2': '分析标题、主图、评价、定位与价格带',
    'pricing.module.pa.b3': '输出可执行的商品与页面优化建议',
    'pricing.module.cs.title': 'Content Strategy',
    'pricing.module.cs.b1': '把市场信号转化为可发布的内容机会',
    'pricing.module.cs.b2': '生成角度、钩子、标题与 campaign 思路',
    'pricing.module.cs.b3': '支持跨境增长与产品营销落地',
    'pricing.module.wf.title': 'Workflow Efficiency',
    'pricing.module.wf.b1': '保存报告与历史分析，便于复盘',
    'pricing.module.wf.b2': '更快回到关键分析会话',
    'pricing.module.wf.b3': '为团队协作与规模化流程做好准备',
    'pricing.entitlementRow.free.productAnalyses': '商品分析：预览额度',
    'pricing.entitlementRow.free.marketReports': '市场情报：预览额度',
    'pricing.entitlementRow.free.history': '历史：基础保留',
    'pricing.entitlementRow.free.teamSeats': '席位：1',
    'pricing.entitlementRow.free.support': '支持：文档与社区',
    'pricing.entitlementRow.free.contentStrategy': '内容策略：入门可用',
    'pricing.entitlementRow.free.advancedProduct': '高级商品解析：未包含',
    'pricing.entitlementRow.pro.productAnalyses': '商品分析：更高月度额度（预览）',
    'pricing.entitlementRow.pro.marketReports': '市场情报：更高月度额度（预览）',
    'pricing.entitlementRow.pro.history': '历史：扩展保留',
    'pricing.entitlementRow.pro.teamSeats': '席位：1（可升级）',
    'pricing.entitlementRow.pro.support': '支持：优先响应',
    'pricing.entitlementRow.pro.contentStrategy': '内容策略：完整可用',
    'pricing.entitlementRow.pro.advancedProduct': '高级商品解析：包含',
    'pricing.entitlementRow.team.productAnalyses': '商品分析：团队配额（按约定）',
    'pricing.entitlementRow.team.marketReports': '市场情报：团队配额（按约定）',
    'pricing.entitlementRow.team.history': '历史：团队共享池',
    'pricing.entitlementRow.team.teamSeats': '席位：多席位（按约定）',
    'pricing.entitlementRow.team.support': '支持：专属客户成功',
    'pricing.entitlementRow.team.contentStrategy': '内容策略：团队级',
    'pricing.entitlementRow.team.advancedProduct': '高级商品解析：团队级',
    'checkout.title': '结算',
    'checkout.subtitle': '确认方案与账单信息。支付接入前本页仅展示，不产生真实扣款。',
    'checkout.back': '返回',
    'checkout.backPricing': '返回定价',
    'checkout.invalid': '链接无效或缺少套餐参数。',
    'checkout.summary.title': '订单摘要',
    'checkout.summary.plan': '方案',
    'checkout.summary.cycle': '计费周期',
    'checkout.summary.listAnnual': '年付原价（按月折算）',
    'checkout.summary.subtotal': '小计',
    'checkout.summary.savings': '年付节省',
    'checkout.summary.total': '合计',
    'checkout.summary.contact': '联系销售',
    'checkout.summary.taxNote': '税费以实际支付服务商与地区为准；当前不扣款。',
    'checkout.price.zero': '$0',
    'checkout.price.perMonthSuffix': ' / 月',
    'checkout.price.perYearSuffix': ' / 年',
    'checkout.payment.title': '支付方式',
    'checkout.payment.skipNotice': '当前方案无需在线支付。以下为将来接入的支付方式占位。',
    'checkout.billing.title': '账单信息',
    'checkout.billing.email': '邮箱',
    'checkout.billing.emailPlaceholder': 'name@company.com',
    'checkout.billing.company': '公司名称（可选）',
    'checkout.billing.companyPlaceholder': '您的公司或品牌名',
    'checkout.billing.country': '国家 / 地区',
    'checkout.billing.countryPlaceholder': '例如：United States',
    'checkout.confirm.cta': '继续支付（即将开通）',
    'checkout.confirm.hint': '支付提供商接入前按钮保持禁用，不会发起扣款。',
    'checkout.confirm.reasonTitle': '暂时无法完成支付',
    'checkout.confirm.globalBlock': '结账需先完成支付服务商对接与商户配置；完成前系统不会授权扣款。',
    'checkout.confirm.selectedRail': '当前选择',
    'checkout.confirm.selectRailHint': '请选择一种支付方式以查看说明（预览，不会扣款）。',
    'payment.method.wechat': 'WeChat Pay',
    'payment.method.wechat.desc': '微信支付',
    'payment.method.alipay': 'Alipay',
    'payment.method.alipay.desc': '支付宝',
    'payment.method.apple': 'Apple Pay',
    'payment.method.apple.desc': 'Apple 钱包',
    'payment.method.card': '银行卡',
    'payment.method.card.desc': 'Visa / Mastercard 等',
    'payment.badge.pendingIntegration': '接入中',
    'payment.badge.providerDisconnected': '未连接',
    'payment.badge.ready': '可用',
    'payment.availability.wechat': '该支付方式正在接入中，完成后即可在合规前提下发起支付。',
    'payment.availability.alipay': '该支付方式正在接入中，完成后即可在合规前提下发起支付。',
    'payment.availability.apple': 'Apple Pay 需完成商户与收银配置后启用。',
    'payment.availability.card': '银行卡支付需先连接收单服务；当前尚未绑定提供商。',
    'workspace.upgrade': '升级方案',
    'workspace.upgradeHint': '了解套餐与用量',

    // Common
    'common.start': '开始使用',
    'common.tryFree': '免费试用',
    'common.tryFreeNow': '开始免费试用',
    'common.learnMore': '了解更多',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.product': 'Product',
    'nav.shortDrama': 'Short Drama',
    'nav.cases': 'Cases',
    'nav.about': 'About',
    'nav.workspace': 'Workspace',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.pricing': 'Pricing',
    'home.pricingLink': 'View plans & pricing',

    // Home
    'home.hero.title': 'The AI marketing and product growth workspace for global teams',
    'home.hero.subtitle':
      'Bring market insight, content production, product analysis, and execution handoff into one workflow—so your team finds opportunities faster, ships content, and optimizes listings.',
    'home.hero.primary': 'Open Workspace',
    'home.hero.secondary': 'View pricing',
    'home.capabilities.title': 'Capabilities at a glance',
    'home.capabilities.subtitle':
      'From market judgment to content and product moves, GlobalPulseAI connects the critical steps in one workflow.',
    'home.capabilities.l1':
      'Marketing analysis: turn scattered market signals into needs, trends, and competitive judgment.',
    'home.capabilities.l2':
      'Content production: turn insight into directions, topics, and ready-to-use expression.',
    'home.capabilities.l3':
      'Product analysis: turn listings, reviews, and selling points into optimization suggestions.',
    'home.capabilities.l4':
      'Workflow continuity: keep analyses, history, and next steps in the same workspace.',
    'home.howItWorks.heading': 'How it works',
    'home.step1': 'Enter your market, content, or product question',
    'home.step2': 'The system integrates multi-source signals and completes analysis',
    'home.step3': 'Deliver actionable content, product, and next-step outputs',
    'home.output.title': 'What you ultimately get',
    'home.output.b1': 'Market insight: needs, trends, competitive gaps, and user pain points',
    'home.output.b2': 'Content direction: topics to try, angles, and content directions',
    'home.output.b3':
      'Product suggestions: titles, hero images, selling points, review signals, and page optimization',
    'home.output.b4': 'Execution handoff: history, conclusions, and next-step management',
    'home.cta.title': 'What is next',
    'home.cta.desc': 'Start in Workspace; compare plans on Pricing, or explore product capabilities first.',
    'home.cta.product': 'Explore product',
    'home.analyzing': '正在分析市场数据...',
    'home.analyzing.en': 'Analyzing market data...',
    'home.analysisFailed': '分析失败，请稍后重试',
    'home.analysisFailed.en': 'Analysis failed, please try again later',

    // Product
    'product.title': 'Product Features',
    'product.subtitle': 'Comprehensive market analysis solutions to help you seize marketing opportunities',
    'product.feature1.title': 'Demand Analysis',
    'product.feature1.desc': 'Deep dive into Reddit community discussions to mine real user needs and market pain points, precisely understanding target audience',
    'product.feature1.f1': 'Topic Extraction',
    'product.feature1.f2': 'Sentiment Analysis',
    'product.feature1.f3': 'Trend Identification',
    'product.feature2.title': 'Competition Analysis',
    'product.feature2.desc': 'Comprehensive scan of SEO content supply, analyze competitor strategies, identify market gaps and opportunities',
    'product.feature2.f1': 'Keyword Analysis',
    'product.feature2.f2': 'Content Statistics',
    'product.feature2.f3': 'Gap Identification',
    'product.feature3.title': 'Smart Recommendation',
    'product.feature3.desc': 'Based on demand-supply comparison analysis, automatically generate high-value content ideas to improve marketing efficiency',
    'product.feature3.f1': 'Idea Generation',
    'product.feature3.f2': 'Format Diversity',
    'product.feature3.f3': 'Reason Explanation',
    'product.feature4.title': 'Data Insights',
    'product.feature4.desc': 'Integrate multiple data sources to provide key metrics like opportunity scores and market trends to support decisions',
    'product.feature4.f1': 'Visual Reports',
    'product.feature4.f2': 'Data Export',
    'product.feature4.f3': 'History Tracking',
    'product.cta.title': 'Get Started',
    'product.cta.desc': 'Experience the powerful analysis capabilities of GlobalPulse AI now and discover your next market opportunity',
    'product.cta.button': 'Try Free',

    // Cases
    'cases.title': 'Success Stories',
    'cases.subtitle': 'See how other businesses use GlobalPulse AI to achieve results',
    'cases.tag1': 'SaaS',
    'cases.case1.title': 'AI Tool Promotion',
    'cases.case1.client': 'AI Coding Assistant Company',
    'cases.case1.desc': 'By analyzing Reddit discussion hotspots, discovered real user needs for AI coding tools, generated targeted content strategies.',
    'cases.tag2': 'E-commerce',
    'cases.case2.title': 'Shopify SEO Optimization',
    'cases.case2.client': 'Cross-border E-commerce Platform',
    'cases.case2.desc': 'Analyzed the gap between SEO supply and Reddit demand, found low-competition high-value keywords, optimized content strategy.',
    'cases.tag3': 'Marketing',
    'cases.case3.title': 'Content Marketing Transformation',
    'cases.case3.client': 'Marketing Automation Service Provider',
    'cases.case3.desc': 'Leveraged intelligent content idea generation to quickly produce high-quality marketing content, significantly improved market response speed.',
    'cases.tag4': 'Education',
    'cases.case4.title': 'Online Course Promotion',
    'cases.case4.client': 'Online Education Platform',
    'cases.case4.desc': 'Analyzed learner discussions on Reddit, discovered pain points and opportunities for course promotion, precisely targeted users.',
    'cases.tag5': 'Tech',
    'cases.case5.title': 'Developer Tool Promotion',
    'cases.case5.client': 'Developer Tool Vendor',
    'cases.case5.desc': 'By analyzing discussion trends in developer communities, created content that meets needs, enhanced brand awareness among target audience.',
    'cases.tag6': 'Consulting',
    'cases.case6.title': 'B2B Marketing Optimization',
    'cases.case6.client': 'B2B Software Service Provider',
    'cases.case6.desc': 'Analyzed B2B decision makers\' concerns, generated professional content, improved lead quality and conversion efficiency.',
    'cases.cta.title': 'Be the Next Success Story',
    'cases.cta.desc': 'Start using GlobalPulse AI now and discover market opportunities for you',
    'cases.cta.button': 'Start Free Trial',
    'cases.r1.label': 'Content Opportunities',
    'cases.r2.label': 'Traffic Growth',
    'cases.r3.label': 'Conversion Increase',
    'cases.r4.label': 'Keyword Opportunities',
    'cases.r5.label': 'Search Ranking',
    'cases.r6.label': 'ROI Increase',
    'cases.r7.label': 'Idea Generation',
    'cases.r8.label': 'Creation Efficiency',
    'cases.r9.label': 'User Engagement',
    'cases.r10.label': 'Market Insights',
    'cases.r11.label': 'Enrollment Conversion',
    'cases.r12.label': 'Content Output',
    'cases.r13.label': 'Community Influence',
    'cases.r14.label': 'Organic Traffic',
    'cases.r15.label': 'Brand Awareness',
    'cases.r16.label': 'Lead Quality',
    'cases.r17.label': 'Sales Cycle',
    'cases.r18.label': 'Market Coverage',

    // About
    'about.title': 'About Us',
    'about.subtitle': 'Empowering marketing with AI technology to help businesses discover opportunities in data',
    'about.hero.primary': 'Open Workspace',
    'about.hero.secondary': 'View pricing',
    'about.story.eyebrow': 'Story & why',
    'about.story.title': 'Why we built GlobalPulse AI',
    'about.story.p1':
      'Marketing and content decisions increasingly depend on real-time signals—but data is fragmented and tools don’t connect, so teams struggle to turn inputs into action. We use AI to unify sources into clear insight and concrete next steps you can try.',
    'about.story.p2':
      'From NLP to multi-source analytics, we keep refining the workflow so marketers and creators spend less time wrangling data and more on strategy and creativity.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'GlobalPulse AI is committed to helping enterprises and marketers gain real-time market insights, deeply analyze user needs, discover content opportunities, and make smarter marketing decisions through advanced AI technology. We believe data-driven marketing strategies are key to future success.',
    'about.values.title': 'Our Values',
    'about.values.precise.title': 'Precision',
    'about.values.precise.desc': 'Based on real data and AI analysis, provide precise market insights and content recommendations, no blind guessing',
    'about.values.efficient.title': 'Efficiency',
    'about.values.efficient.desc': 'Automated analysis processes, greatly improve marketing efficiency, let teams focus on creativity and strategy',
    'about.values.reliable.title': 'Reliability',
    'about.values.reliable.desc': 'Authoritative data sources, rigorous analysis algorithms, verifiable results, worth your trust',
    'about.why.title': 'Why Choose Us',
    'about.why.1.title': 'AI-Powered Analysis',
    'about.why.1.desc': 'Leverage cutting-edge natural language processing and machine learning to deeply mine social media and SEO data',
    'about.why.2.title': 'Multi-Dimensional Data Integration',
    'about.why.2.desc': 'Analyze multiple data sources like Reddit, SEO simultaneously, providing comprehensive market perspectives',
    'about.why.3.title': 'Real-Time Market Insights',
    'about.why.3.desc': 'Capture latest trends and hotspots, help you quickly respond to market changes',
    'about.why.4.title': 'Actionable Recommendations',
    'about.why.4.desc': 'Not just data reports, but directly executable content ideas and strategy recommendations',
    'about.contact.title': 'Contact Us',
    'about.contact.email': 'Email Contact',
    'about.contact.email.value': 'chuckyang360@gmail.com',
    'about.contact.follow': 'Follow Us',
    'about.contact.follow.value': '@GlobalPulseAI',
    'about.contact.address': 'Company Address',
    'about.contact.address.value': 'Hangzhou Yuexiang Information Technology Co., Ltd.',
    'about.contact.person': 'Contact Person',
    'about.contact.person.value': 'Yang Ke',
    'about.cta.title': 'Ready to Start?',
    'about.cta.desc': 'Join GlobalPulse AI and let data drive your marketing decisions',
    'about.cta.button': 'Start for Free',

    // Pricing & Checkout
    'pricing.page.eyebrow': 'Plans',
    'pricing.page.title': 'Choose your plan',
    'pricing.page.subtitle':
      'GlobalPulseAI connects market intelligence, product analysis, content strategy, and workflow efficiency—turning cross-platform signals into actionable growth.',
    'pricing.page.subtitleShort': 'Market intelligence, product analysis, and content strategy—pick a plan that fits.',
    'pricing.page.proOneLiner': 'When you need higher-frequency insight and depth, most teams choose Pro.',
    'pricing.page.footerNote':
      'Prices shown are placeholders until payments go live. Usage limits follow your account and agreement; contact sales for questions.',
    'pricing.plan.pro.cardHint': 'Built for weekly iteration and multiple listings in parallel.',
    'pricing.pro.section.title': 'Why most teams start with Pro',
    'pricing.pro.section.body':
      'Creators, sellers, and operators need a steady cadence: turn trends, conversations, and listing gaps into iterative optimizations and content moves. Pro matches that pace with higher limits and depth.',
    'pricing.modules.sectionTitle': 'Capability map',
    'pricing.toggle.monthly': 'Monthly',
    'pricing.toggle.yearly': 'Yearly',
    'pricing.toggle.save': 'Save {n}%',
    'pricing.billing.perMonthShort': '/mo',
    'pricing.billing.perYearShort': '/yr',
    'pricing.billing.equivalentMonthly': '≈ ${n}/mo billed annually',
    'pricing.plan.pro.badge': 'Popular',
    'pricing.cta.checkout': 'Continue to checkout',
    'pricing.cta.contact': 'Contact sales',
    'pricing.usage.heading': 'Usage & entitlements (preview)',
    'pricing.plan.free.name': 'Free',
    'pricing.plan.free.audience': 'Best for: exploration & validation',
    'pricing.plan.free.tagline': 'Validate the market before you scale spend.',
    'pricing.plan.free.priceHint': 'Forever free',
    'pricing.plan.free.f1': 'Turn trends and threads into a short follow-up list',
    'pricing.plan.free.f2': 'Turn a product link into actionable first-pass insights',
    'pricing.plan.free.f3': 'Turn signals into starter angles to ship content sooner',
    'pricing.plan.free.f4': 'Save key snippets so your next session starts faster',
    'pricing.plan.pro.name': 'Pro',
    'pricing.plan.pro.audience': 'Best for: sellers, creators, and operators',
    'pricing.plan.pro.tagline': 'Make “spot trend → understand listing → ship the next move” a weekly rhythm.',
    'pricing.plan.pro.whyRecommended':
      'Solo sellers and creators run parallel experiments across channels and listings. Pro raises the ceiling on insight depth and iteration speed so you spend time improving listings and creatives—not hunting the same charts again.',
    'pricing.plan.pro.f1': 'Connect Reddit, X, and search signals to judge real demand',
    'pricing.plan.pro.f2': 'Turn product pages into prioritized optimization recommendations',
    'pricing.plan.pro.f3': 'Turn insights into publish-ready angles, hooks, and titles',
    'pricing.plan.pro.f4': 'Use reports and history to link tests to the next change',
    'pricing.plan.pro.f5': 'Early access to new capabilities as they ship',
    'pricing.plan.team.name': 'Team',
    'pricing.plan.team.audience': 'Best for: multi-brand teams and cross-functional growth',
    'pricing.plan.team.tagline': 'Room for collaboration and scale: shared context, coordinated cadence, expandable quotas.',
    'pricing.team.priceLine': 'Contact sales',
    'pricing.team.priceHint': 'Custom seats, usage, and compliance',
    'pricing.plan.team.f1': 'Shared market and listing context—fewer repeated questions',
    'pricing.plan.team.f2': 'Scale analysis capacity as you add stores and categories',
    'pricing.plan.team.f3': 'Centralized billing, access, and procurement',
    'pricing.plan.team.f4': 'Turn history into team memory—not scattered sessions',
    'pricing.plan.team.f5': 'Success and priority support for rollout at scale',
    'pricing.module.mi.title': 'Market Intelligence',
    'pricing.module.mi.b1': 'Discover cross-platform trends',
    'pricing.module.mi.b2': 'Track conversations from Reddit, X, and search signals',
    'pricing.module.mi.b3': 'Identify demand, sentiment, and opportunities',
    'pricing.module.pa.title': 'Product Analysis',
    'pricing.module.pa.b1': 'Parse product links from major commerce platforms',
    'pricing.module.pa.b2': 'Analyze title, images, reviews, positioning, and pricing',
    'pricing.module.pa.b3': 'Generate actionable product improvement suggestions',
    'pricing.module.cs.title': 'Content Strategy',
    'pricing.module.cs.b1': 'Turn market signals into content opportunities',
    'pricing.module.cs.b2': 'Generate angles, hooks, titles, and campaign ideas',
    'pricing.module.cs.b3': 'Support cross-border growth and product marketing execution',
    'pricing.module.wf.title': 'Workflow Efficiency',
    'pricing.module.wf.b1': 'Save reports and historical analysis',
    'pricing.module.wf.b2': 'Revisit analysis sessions faster',
    'pricing.module.wf.b3': 'Prepare for team collaboration and scalable workflows',
    'pricing.entitlementRow.free.productAnalyses': 'Product analyses: preview quota',
    'pricing.entitlementRow.free.marketReports': 'Market intelligence: preview quota',
    'pricing.entitlementRow.free.history': 'History: basic retention',
    'pricing.entitlementRow.free.teamSeats': 'Seats: 1',
    'pricing.entitlementRow.free.support': 'Support: docs & community',
    'pricing.entitlementRow.free.contentStrategy': 'Content strategy: starter access',
    'pricing.entitlementRow.free.advancedProduct': 'Advanced product analysis: not included',
    'pricing.entitlementRow.pro.productAnalyses': 'Product analyses: higher monthly quota (preview)',
    'pricing.entitlementRow.pro.marketReports': 'Market intelligence: higher monthly quota (preview)',
    'pricing.entitlementRow.pro.history': 'History: extended retention',
    'pricing.entitlementRow.pro.teamSeats': 'Seats: 1 (upgradeable)',
    'pricing.entitlementRow.pro.support': 'Support: priority response',
    'pricing.entitlementRow.pro.contentStrategy': 'Content strategy: full access',
    'pricing.entitlementRow.pro.advancedProduct': 'Advanced product analysis: included',
    'pricing.entitlementRow.team.productAnalyses': 'Product analyses: team quota (as agreed)',
    'pricing.entitlementRow.team.marketReports': 'Market intelligence: team quota (as agreed)',
    'pricing.entitlementRow.team.history': 'History: shared team pool',
    'pricing.entitlementRow.team.teamSeats': 'Seats: multi-seat (as agreed)',
    'pricing.entitlementRow.team.support': 'Support: dedicated success',
    'pricing.entitlementRow.team.contentStrategy': 'Content strategy: team-wide',
    'pricing.entitlementRow.team.advancedProduct': 'Advanced product analysis: team-wide',
    'checkout.title': 'Checkout',
    'checkout.subtitle': 'Review your plan and billing details. No real charges until payment is connected.',
    'checkout.back': 'Back',
    'checkout.backPricing': 'Back to pricing',
    'checkout.invalid': 'Invalid or missing plan in the URL.',
    'checkout.summary.title': 'Plan summary',
    'checkout.summary.plan': 'Plan',
    'checkout.summary.cycle': 'Billing cycle',
    'checkout.summary.listAnnual': 'List price (monthly × 12)',
    'checkout.summary.subtotal': 'Subtotal',
    'checkout.summary.savings': 'Annual savings',
    'checkout.summary.total': 'Total',
    'checkout.summary.contact': 'Contact sales',
    'checkout.summary.taxNote': 'Taxes depend on your provider and region. No charge at this stage.',
    'checkout.price.zero': '$0',
    'checkout.price.perMonthSuffix': '/month',
    'checkout.price.perYearSuffix': '/year',
    'checkout.payment.title': 'Payment methods',
    'checkout.payment.skipNotice': 'No online payment for this selection. Options below are future rails.',
    'checkout.billing.title': 'Billing information',
    'checkout.billing.email': 'Email',
    'checkout.billing.emailPlaceholder': 'name@company.com',
    'checkout.billing.company': 'Company (optional)',
    'checkout.billing.companyPlaceholder': 'Your company or brand',
    'checkout.billing.country': 'Country / Region',
    'checkout.billing.countryPlaceholder': 'e.g. United States',
    'checkout.confirm.cta': 'Continue to pay (coming soon)',
    'checkout.confirm.hint': 'Disabled until payment providers are connected—no charges.',
    'checkout.confirm.reasonTitle': 'Payment not available yet',
    'checkout.confirm.globalBlock':
      'Checkout requires a connected payment provider and merchant setup. No charges are authorized before that.',
    'checkout.confirm.selectedRail': 'Selected method',
    'checkout.confirm.selectRailHint': 'Select a payment method to see details (preview only—no charges).',
    'payment.method.wechat': 'WeChat Pay',
    'payment.method.wechat.desc': 'WeChat wallet',
    'payment.method.alipay': 'Alipay',
    'payment.method.alipay.desc': 'Alipay checkout',
    'payment.method.apple': 'Apple Pay',
    'payment.method.apple.desc': 'Apple Wallet',
    'payment.method.card': 'Card',
    'payment.method.card.desc': 'Visa, Mastercard, and more',
    'payment.badge.pendingIntegration': 'Connecting',
    'payment.badge.providerDisconnected': 'Not connected',
    'payment.badge.ready': 'Ready',
    'payment.availability.wechat': 'This payment method is being connected; you will be able to pay once integration is complete.',
    'payment.availability.alipay': 'This payment method is being connected; you will be able to pay once integration is complete.',
    'payment.availability.apple': 'Apple Pay will be available after merchant and checkout setup.',
    'payment.availability.card': 'Card payments require a connected payment processor; none is bound yet.',
    'workspace.upgrade': 'Upgrade plan',
    'workspace.upgradeHint': 'See plans & usage',

    // Common
    'common.start': 'Get Started',
    'common.tryFree': 'Try Free',
    'common.tryFreeNow': 'Start Free Trial',
    'common.learnMore': 'Learn More',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('gp_language') as Language;
    return saved && (saved === 'zh' || saved === 'en') ? saved : 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('gp_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
